config/routes.rb
Rails.application.routes.draw do
  get 'post/index'

  get 'post/show'

  get 'post/edit'

  get 'post/destroy'

  get 'post/update'

  get 'welcome/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, only: [:show, :index, :edit, :destroy, :update]
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  TEMP_PHONE_PREFIX = '5555555555'
  TEMP_PHONE_REGEX = /\A555-555-5555/

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :omniauthable, :omniauth_providers => [:facebook]

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  validates_format_of :phone, :without => TEMP_PHONE_REGEX, on: :update
  # attr_accessible :email, :last_name, :first_name, :gender, :uid, :profile_picture, :link, :provider, :oauth_token, :oauth_expires_at    
  validates_presence_of :first_name, :last_name, :email, :phone
  validates_uniqueness_of :email
  serialize :friends
  enum access_level: [:user, :admin, :super_admin]

  def self.find_for_oauth(auth, signed_in_resource = nil)
    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?
      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email


      # Create the user if it's a new registration
      if user.nil?
        # request the list of friends for the user
        friends = koala(auth.credentials)
	phone_temp = "555-555-5555"
	# insert all the data into the db
        user = User.new(first_name:auth.extra.raw_info.first_name,last_name:auth.extra.raw_info.last_name,gender:auth.extra.raw_info.gender,profile_picture:auth.info.image,link:auth.extra.raw_info.link,email: auth.info.email,age_min:auth.extra.raw_info.age_range.min[1],age_max:auth.extra.raw_info.age_range.max[1], password: Devise.friendly_token[0,20], friends: friends, phone: phone_temp, access_level: 2)
        user.skip_confirmation!
	#user.skip_confirmation! if user.respond_to?(:skip_confirmation)
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def phone_verified?
    self.phone && self.phone !~ TEMP_PHONE_REGEX
  end
  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
  
  private

  def self.koala(auth)
    access_token = auth.token
    facebook = Koala::Facebook::API.new(access_token)
    #facebook.get_object("me?fields=name,picture")    
    friends = facebook.get_connections("me", "friends")
    return friends
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  #before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]

  before_action :set_user, :finish_signup
  before_filter :authenticate_user!
  before_filter :ensure_signup_complete, only: [:new, :create, :update, :destroy]


 def index
    #authorize! 
    @users = User.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    unless current_user.admin? || current_user.super_admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  # GET /users/:id.:format
  def show
    @user = User.find(params[:id])
    # authorize! :read, @user
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      #if @user.update(user_params)
      #  @user.skip_reconfirmation!
      if current_user.update(user_params)
        current_user.skip_reconfirmation!
        sign_in(current_user, :bypass => true)
        redirect_to users_path, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end


  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user = User.find(params[:id])
    if @user.destroy
        flash[:notice] = "User Removed"
        redirect_to root_path
    else
        render 'destroy'
    end
  end

  private
    def set_user
      #@user = User.find(params[:id])
      #@user = User.find(params[:id])
    end

    def user_params
      accessible = [ :first_name, :last_name, :gender, :profile_picture, :link, :email, :age_min, :age_max, :friends, :phone ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/views/users/edit.html.erb
<h2>Edit User</h2>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %> </div>
    <% end %>
<% end %>
<%= form_for [@user] do |f| %>
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <%= f.text_field :first_name, :placeholder => "first name", class:'form-control' %>
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <%= f.text_field :last_name, :placeholder => "last name", class:'form-control' %>
            </div>
        </div>
    </div>

    <div class="form-group">
        <%= f.text_field :gender, :placeholder =>"email", class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.email_field :email, :placeholder =>"email", class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.telephone_field :phone, :placeholder =>"555-555-5555", class:'form-control' %>
    </div>

    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <%= f.password_field :password, :placeholder => "new password", class:'form-control' %>
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <%= f.password_field :password_confirmation, :placeholder => "confirm new password", class:'form-control' %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <%= f.submit "Update", class:'btn btn-info btn-block' %>
        </div>       
        <div class="col-xs-6 col-sm-6 col-md-6">
            <%= link_to "Cancel", users_path, class:'btn btn-danger btn-block' %>
        </div> 
    </div>      
<% end %>

app/views/users/finish_signup.html.erb
<div id="add-phone" class="container">
  <h1>Add Phone</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :phone %>
      <div class="controls">
        <%= f.text_field :phone, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: 555-555-5555' %>
        <p class="help-block">Please confirm your phone number. We will never call you or give our your number.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h2 class="page-header">Manage Users <%= link_to "Create New",  new_user_registration_path, class:'btn btn-success pull-right'%></h2> 
    <% if @users.exists? %>
              <table class="table table-striped">
                <tr>
                  <th>Role </th>
                  <th>User's Full Name</th>
                  <th>Gender</th>
                  <th>Email</th>
                  <th>Phone Number</th>
                  <th>Facebook Picture </th>
                  <th>Min Age</th>
                  <th>Max Age</th>
                  <th>Create Date </th>
                  <th>Last Sign In </th>
                  <th>Sign In Count </th>
                  <th>Actions</th>
              </tr>
              <% @users.each do |user| %>
                <tr>
                    <td><%= user.access_level %></td>
                    <td><%= link_to (user.first_name + ' ' + user.last_name), user.link %></td>
           	    <td><%= user.gender %></td>
                    <td><%= user.email %></td>
                    <td><%= user.phone %></td>
                    <td><%= image_tag user.profile_picture %></td>
                    <td><%= user.age_min %></td>
                    <td><%= user.age_max %></td>
                    <td><%= user.created_at.to_time.strftime('%B %e at %l:%M %p' ) %></td>
                    <td><%= user.last_sign_in_at.to_time.strftime('%B %e at %l:%M %p' ) %></td>
                    <td><%= user.sign_in_count %></td>
                    <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-primary' %> <%= link_to 'Delete', user_path(user), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?" } %></td>
                </tr>
            <% end %>
            </table>
        <%= will_paginate @users %>
    <% else %>
        <p>There are no users</p>
    <% end %>

app/views/users/show.html.erb
<p>find me in /view/users/show.html.erb</p>
<%= link_to 'See all users',users_path  %>